// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

package essam.com.example.Shift.Application.grpc;

public final class Gigs {
  private Gigs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017myservice.proto\022#essam.com.example.Shi" +
      "ft.Application\"\034\n\014HelloRequest\022\014\n\004name\030\001" +
      " \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2x\n\006S" +
      "imple\022n\n\010SayHello\0221.essam.com.example.Sh" +
      "ift.Application.HelloRequest\032/.essam.com" +
      ".example.Shift.Application.HelloReplyB2\n" +
      "(essam.com.example.Shift.Application.grp" +
      "cB\004GigsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_essam_com_example_Shift_Application_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_essam_com_example_Shift_Application_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_essam_com_example_Shift_Application_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_essam_com_example_Shift_Application_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
