// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

package essam.com.example.Shift.Application.grpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
