// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

package essam.com.example.Shift.Application.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
