// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package essam.com.example.Shift.Application.grpc;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
