// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package essam.com.example.Shift.Application.grpc;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phoneNumber = 1;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
