// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shifts.proto

package essam.com.example.Shift.Application.grpc;

public final class Shifts {
  private Shifts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateShiftRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.CreateShiftRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 startTime = 1;</code>
     */
    long getStartTime();

    /**
     * <code>int64 endTime = 2;</code>
     */
    long getEndTime();
  }
  /**
   * Protobuf type {@code essam.com.example.Shift.Application.CreateShiftRequest}
   */
  public  static final class CreateShiftRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essam.com.example.Shift.Application.CreateShiftRequest)
      CreateShiftRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateShiftRequest.newBuilder() to construct.
    private CreateShiftRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateShiftRequest() {
      startTime_ = 0L;
      endTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateShiftRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startTime_ = input.readInt64();
              break;
            }
            case 16: {

              endTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_CreateShiftRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.class, essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.Builder.class);
    }

    public static final int STARTTIME_FIELD_NUMBER = 1;
    private long startTime_;
    /**
     * <code>int64 startTime = 1;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private long endTime_;
    /**
     * <code>int64 endTime = 2;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startTime_ != 0L) {
        output.writeInt64(1, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(2, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest)) {
        return super.equals(obj);
      }
      essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest other = (essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest) obj;

      boolean result = true;
      result = result && (getStartTime()
          == other.getStartTime());
      result = result && (getEndTime()
          == other.getEndTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essam.com.example.Shift.Application.CreateShiftRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essam.com.example.Shift.Application.CreateShiftRequest)
        essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_CreateShiftRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.class, essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.Builder.class);
      }

      // Construct using essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startTime_ = 0L;

        endTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest getDefaultInstanceForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.getDefaultInstance();
      }

      public essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest build() {
        essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest buildPartial() {
        essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest result = new essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest(this);
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest) {
          return mergeFrom((essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest other) {
        if (other == essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest.getDefaultInstance()) return this;
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 startTime = 1;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 1;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 2;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 2;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essam.com.example.Shift.Application.CreateShiftRequest)
    }

    // @@protoc_insertion_point(class_scope:essam.com.example.Shift.Application.CreateShiftRequest)
    private static final essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest();
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateShiftRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateShiftRequest>() {
      public CreateShiftRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateShiftRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateShiftRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateShiftRequest> getParserForType() {
      return PARSER;
    }

    public essam.com.example.Shift.Application.grpc.Shifts.CreateShiftRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindOneShiftRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.FindOneShiftRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code essam.com.example.Shift.Application.FindOneShiftRequest}
   */
  public  static final class FindOneShiftRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essam.com.example.Shift.Application.FindOneShiftRequest)
      FindOneShiftRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindOneShiftRequest.newBuilder() to construct.
    private FindOneShiftRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindOneShiftRequest() {
      id_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindOneShiftRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.class, essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest)) {
        return super.equals(obj);
      }
      essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest other = (essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essam.com.example.Shift.Application.FindOneShiftRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essam.com.example.Shift.Application.FindOneShiftRequest)
        essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.class, essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.Builder.class);
      }

      // Construct using essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest getDefaultInstanceForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.getDefaultInstance();
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest build() {
        essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest buildPartial() {
        essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest result = new essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest) {
          return mergeFrom((essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest other) {
        if (other == essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essam.com.example.Shift.Application.FindOneShiftRequest)
    }

    // @@protoc_insertion_point(class_scope:essam.com.example.Shift.Application.FindOneShiftRequest)
    private static final essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest();
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindOneShiftRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindOneShiftRequest>() {
      public FindOneShiftRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindOneShiftRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindOneShiftRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindOneShiftRequest> getParserForType() {
      return PARSER;
    }

    public essam.com.example.Shift.Application.grpc.Shifts.FindOneShiftRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OneShiftResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.OneShiftResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>float startTime = 2;</code>
     */
    float getStartTime();

    /**
     * <code>float endTime = 3;</code>
     */
    float getEndTime();
  }
  /**
   * Protobuf type {@code essam.com.example.Shift.Application.OneShiftResponse}
   */
  public  static final class OneShiftResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essam.com.example.Shift.Application.OneShiftResponse)
      OneShiftResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneShiftResponse.newBuilder() to construct.
    private OneShiftResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneShiftResponse() {
      id_ = 0L;
      startTime_ = 0F;
      endTime_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneShiftResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 21: {

              startTime_ = input.readFloat();
              break;
            }
            case 29: {

              endTime_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_OneShiftResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.class, essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private float startTime_;
    /**
     * <code>float startTime = 2;</code>
     */
    public float getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private float endTime_;
    /**
     * <code>float endTime = 3;</code>
     */
    public float getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (startTime_ != 0F) {
        output.writeFloat(2, startTime_);
      }
      if (endTime_ != 0F) {
        output.writeFloat(3, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (startTime_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, startTime_);
      }
      if (endTime_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse)) {
        return super.equals(obj);
      }
      essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse other = (essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Float.floatToIntBits(getStartTime())
          == java.lang.Float.floatToIntBits(
              other.getStartTime()));
      result = result && (
          java.lang.Float.floatToIntBits(getEndTime())
          == java.lang.Float.floatToIntBits(
              other.getEndTime()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getEndTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essam.com.example.Shift.Application.OneShiftResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essam.com.example.Shift.Application.OneShiftResponse)
        essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_OneShiftResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.class, essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.Builder.class);
      }

      // Construct using essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        startTime_ = 0F;

        endTime_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse getDefaultInstanceForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.getDefaultInstance();
      }

      public essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse build() {
        essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse buildPartial() {
        essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse result = new essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse(this);
        result.id_ = id_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse) {
          return mergeFrom((essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse other) {
        if (other == essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getStartTime() != 0F) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0F) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private float startTime_ ;
      /**
       * <code>float startTime = 2;</code>
       */
      public float getStartTime() {
        return startTime_;
      }
      /**
       * <code>float startTime = 2;</code>
       */
      public Builder setStartTime(float value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float startTime = 2;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = 0F;
        onChanged();
        return this;
      }

      private float endTime_ ;
      /**
       * <code>float endTime = 3;</code>
       */
      public float getEndTime() {
        return endTime_;
      }
      /**
       * <code>float endTime = 3;</code>
       */
      public Builder setEndTime(float value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float endTime = 3;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essam.com.example.Shift.Application.OneShiftResponse)
    }

    // @@protoc_insertion_point(class_scope:essam.com.example.Shift.Application.OneShiftResponse)
    private static final essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse();
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OneShiftResponse>
        PARSER = new com.google.protobuf.AbstractParser<OneShiftResponse>() {
      public OneShiftResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneShiftResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneShiftResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneShiftResponse> getParserForType() {
      return PARSER;
    }

    public essam.com.example.Shift.Application.grpc.Shifts.OneShiftResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FindShiftsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essam.com.example.Shift.Application.FindShifts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 limit = 1;</code>
     */
    long getLimit();

    /**
     * <code>int32 page = 2;</code>
     */
    int getPage();
  }
  /**
   * Protobuf type {@code essam.com.example.Shift.Application.FindShifts}
   */
  public  static final class FindShifts extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essam.com.example.Shift.Application.FindShifts)
      FindShiftsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindShifts.newBuilder() to construct.
    private FindShifts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindShifts() {
      limit_ = 0L;
      page_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindShifts(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              limit_ = input.readInt64();
              break;
            }
            case 16: {

              page_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindShifts_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindShifts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              essam.com.example.Shift.Application.grpc.Shifts.FindShifts.class, essam.com.example.Shift.Application.grpc.Shifts.FindShifts.Builder.class);
    }

    public static final int LIMIT_FIELD_NUMBER = 1;
    private long limit_;
    /**
     * <code>int64 limit = 1;</code>
     */
    public long getLimit() {
      return limit_;
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (limit_ != 0L) {
        output.writeInt64(1, limit_);
      }
      if (page_ != 0) {
        output.writeInt32(2, page_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (limit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, limit_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof essam.com.example.Shift.Application.grpc.Shifts.FindShifts)) {
        return super.equals(obj);
      }
      essam.com.example.Shift.Application.grpc.Shifts.FindShifts other = (essam.com.example.Shift.Application.grpc.Shifts.FindShifts) obj;

      boolean result = true;
      result = result && (getLimit()
          == other.getLimit());
      result = result && (getPage()
          == other.getPage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLimit());
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(essam.com.example.Shift.Application.grpc.Shifts.FindShifts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essam.com.example.Shift.Application.FindShifts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essam.com.example.Shift.Application.FindShifts)
        essam.com.example.Shift.Application.grpc.Shifts.FindShiftsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindShifts_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindShifts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                essam.com.example.Shift.Application.grpc.Shifts.FindShifts.class, essam.com.example.Shift.Application.grpc.Shifts.FindShifts.Builder.class);
      }

      // Construct using essam.com.example.Shift.Application.grpc.Shifts.FindShifts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        limit_ = 0L;

        page_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.internal_static_essam_com_example_Shift_Application_FindShifts_descriptor;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindShifts getDefaultInstanceForType() {
        return essam.com.example.Shift.Application.grpc.Shifts.FindShifts.getDefaultInstance();
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindShifts build() {
        essam.com.example.Shift.Application.grpc.Shifts.FindShifts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public essam.com.example.Shift.Application.grpc.Shifts.FindShifts buildPartial() {
        essam.com.example.Shift.Application.grpc.Shifts.FindShifts result = new essam.com.example.Shift.Application.grpc.Shifts.FindShifts(this);
        result.limit_ = limit_;
        result.page_ = page_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof essam.com.example.Shift.Application.grpc.Shifts.FindShifts) {
          return mergeFrom((essam.com.example.Shift.Application.grpc.Shifts.FindShifts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(essam.com.example.Shift.Application.grpc.Shifts.FindShifts other) {
        if (other == essam.com.example.Shift.Application.grpc.Shifts.FindShifts.getDefaultInstance()) return this;
        if (other.getLimit() != 0L) {
          setLimit(other.getLimit());
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        essam.com.example.Shift.Application.grpc.Shifts.FindShifts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (essam.com.example.Shift.Application.grpc.Shifts.FindShifts) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long limit_ ;
      /**
       * <code>int64 limit = 1;</code>
       */
      public long getLimit() {
        return limit_;
      }
      /**
       * <code>int64 limit = 1;</code>
       */
      public Builder setLimit(long value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 limit = 1;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0L;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 2;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essam.com.example.Shift.Application.FindShifts)
    }

    // @@protoc_insertion_point(class_scope:essam.com.example.Shift.Application.FindShifts)
    private static final essam.com.example.Shift.Application.grpc.Shifts.FindShifts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new essam.com.example.Shift.Application.grpc.Shifts.FindShifts();
    }

    public static essam.com.example.Shift.Application.grpc.Shifts.FindShifts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindShifts>
        PARSER = new com.google.protobuf.AbstractParser<FindShifts>() {
      public FindShifts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindShifts(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindShifts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindShifts> getParserForType() {
      return PARSER;
    }

    public essam.com.example.Shift.Application.grpc.Shifts.FindShifts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_CreateShiftRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_OneShiftResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essam_com_example_Shift_Application_FindShifts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essam_com_example_Shift_Application_FindShifts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014shifts.proto\022#essam.com.example.Shift." +
      "Application\"8\n\022CreateShiftRequest\022\021\n\tsta" +
      "rtTime\030\001 \001(\003\022\017\n\007endTime\030\002 \001(\003\"!\n\023FindOne" +
      "ShiftRequest\022\n\n\002id\030\001 \001(\003\"B\n\020OneShiftResp" +
      "onse\022\n\n\002id\030\001 \001(\003\022\021\n\tstartTime\030\002 \001(\002\022\017\n\007e" +
      "ndTime\030\003 \001(\002\")\n\nFindShifts\022\r\n\005limit\030\001 \001(" +
      "\003\022\014\n\004page\030\002 \001(\0052\373\002\n\014ShiftService\022z\n\007find" +
      "One\0228.essam.com.example.Shift.Applicatio" +
      "n.FindOneShiftRequest\0325.essam.com.exampl" +
      "e.Shift.Application.OneShiftResponse\022p\n\004" +
      "find\022/.essam.com.example.Shift.Applicati" +
      "on.FindShifts\0325.essam.com.example.Shift." +
      "Application.OneShiftResponse0\001\022}\n\013create" +
      "Shift\0227.essam.com.example.Shift.Applicat" +
      "ion.CreateShiftRequest\0325.essam.com.examp" +
      "le.Shift.Application.OneShiftResponseB4\n" +
      "(essam.com.example.Shift.Application.grp" +
      "cB\006ShiftsP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_essam_com_example_Shift_Application_CreateShiftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_CreateShiftRequest_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", });
    internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_FindOneShiftRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_essam_com_example_Shift_Application_OneShiftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_OneShiftResponse_descriptor,
        new java.lang.String[] { "Id", "StartTime", "EndTime", });
    internal_static_essam_com_example_Shift_Application_FindShifts_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_essam_com_example_Shift_Application_FindShifts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essam_com_example_Shift_Application_FindShifts_descriptor,
        new java.lang.String[] { "Limit", "Page", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
